# Generated by Django 5.1.2 on 2024-11-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCountryByEconomic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('web', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('data', models.FloatField()),
            ],
        ),
    ]
